security:
    encoders: 
        App\Entity\User: bcrypt
    providers:
        user_db:
            entity: { class: App\Entity\User, property: username }
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            provider: user_db
            anonymous: ~
            form_login:
                login_path: login
                check_path: login
            logout: true
            anonymous: ~